services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'ahmed'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'ahmed'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'ahmed'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge